name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          platform: win
          arch: x64

        - name: macOS
          os: macos-latest
          platform: mac
          arch: universal

        - name: Android32
          os: ubuntu-latest
          platform: android
          arch: arm32

        - name: Android64
          os: ubuntu-latest
          platform: android
          arch: arm64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Geode SDK
      uses: geode-sdk/setup-geode@main
      with:
        sdk: latest

    - name: Build
      run: geode build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.config.platform }}-${{ matrix.config.arch }}
        path: build/*.geode
